// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyPerspectiveTransform(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyPerspectiveTransform'](arg1, arg2, arg3);
}

export function GetAddonDescription() {
  return window['go']['main']['App']['GetAddonDescription']();
}

export function GetAllReadings() {
  return window['go']['main']['App']['GetAllReadings']();
}

export function GetClickCount() {
  return window['go']['main']['App']['GetClickCount']();
}

export function GetCornerPoints() {
  return window['go']['main']['App']['GetCornerPoints']();
}

export function GetDescription() {
  return window['go']['main']['App']['GetDescription']();
}

export function GetImageDimensions() {
  return window['go']['main']['App']['GetImageDimensions']();
}

export function GetTransformedImage() {
  return window['go']['main']['App']['GetTransformedImage']();
}

export function GetWindowHeight() {
  return window['go']['main']['App']['GetWindowHeight']();
}

export function GetYMax() {
  return window['go']['main']['App']['GetYMax']();
}

export function HandleAddonClick(arg1) {
  return window['go']['main']['App']['HandleAddonClick'](arg1);
}

export function HandleClick(arg1) {
  return window['go']['main']['App']['HandleClick'](arg1);
}

export function IsAddonMode() {
  return window['go']['main']['App']['IsAddonMode']();
}

export function IsPerspectiveMode() {
  return window['go']['main']['App']['IsPerspectiveMode']();
}

export function IsRegularMode() {
  return window['go']['main']['App']['IsRegularMode']();
}

export function Reset() {
  return window['go']['main']['App']['Reset']();
}

export function ResetPerspective() {
  return window['go']['main']['App']['ResetPerspective']();
}

export function SetCornerPoints(arg1) {
  return window['go']['main']['App']['SetCornerPoints'](arg1);
}

export function SetImageDimensions(arg1, arg2) {
  return window['go']['main']['App']['SetImageDimensions'](arg1, arg2);
}

export function SetPerspectiveMode(arg1) {
  return window['go']['main']['App']['SetPerspectiveMode'](arg1);
}

export function SetWindowHeight(arg1) {
  return window['go']['main']['App']['SetWindowHeight'](arg1);
}

export function SetYMax(arg1) {
  return window['go']['main']['App']['SetYMax'](arg1);
}

export function StartAddonUsage() {
  return window['go']['main']['App']['StartAddonUsage']();
}

export function StartRegularUsage() {
  return window['go']['main']['App']['StartRegularUsage']();
}
