// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAddonDescription():Promise<string>;

export function GetAllReadings():Promise<string>;

export function GetClickCount():Promise<number>;

export function GetDescription():Promise<string>;

export function GetWindowHeight():Promise<number>;

export function GetYMax():Promise<number>;

export function HandleAddonClick(arg1:number):Promise<string>;

export function HandleClick(arg1:number):Promise<string>;

export function IsAddonMode():Promise<boolean>;

export function IsRegularMode():Promise<boolean>;

export function Reset():Promise<void>;

export function SetWindowHeight(arg1:number):Promise<void>;

export function SetYMax(arg1:number):Promise<void>;

export function StartAddonUsage():Promise<void>;

export function StartRegularUsage():Promise<void>;
