// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyCrop(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<Array<number>>;

export function ApplyPerspectiveTransform(arg1:Array<number>,arg2:number,arg3:number):Promise<Array<number>>;

export function ApplyPerspectiveTransformParallel(arg1:Array<number>,arg2:number,arg3:number,arg4:any,arg5:any):Promise<Array<number>>;

export function GetAddonDescription():Promise<string>;

export function GetAllReadings():Promise<string>;

export function GetClickCount():Promise<number>;

export function GetCornerPoints():Promise<any>;

export function GetDescription():Promise<string>;

export function GetImageDimensions():Promise<number|number>;

export function GetTransformedImage():Promise<Array<number>>;

export function GetWindowHeight():Promise<number>;

export function GetYMax():Promise<number>;

export function HandleAddonClick(arg1:number):Promise<string>;

export function HandleClick(arg1:number):Promise<string>;

export function IsAddonMode():Promise<boolean>;

export function IsPerspectiveMode():Promise<boolean>;

export function IsRegularMode():Promise<boolean>;

export function Reset():Promise<void>;

export function ResetPerspective():Promise<void>;

export function SetCornerPoints(arg1:any):Promise<void>;

export function SetImageDimensions(arg1:number,arg2:number):Promise<void>;

export function SetPerspectiveMode(arg1:boolean):Promise<void>;

export function SetWindowHeight(arg1:number):Promise<void>;

export function SetYMax(arg1:number):Promise<void>;

export function StartAddonUsage():Promise<void>;

export function StartRegularUsage():Promise<void>;
