// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAddonDescription() {
  return window['go']['main']['App']['GetAddonDescription']();
}

export function GetAllReadings() {
  return window['go']['main']['App']['GetAllReadings']();
}

export function GetClickCount() {
  return window['go']['main']['App']['GetClickCount']();
}

export function GetDescription() {
  return window['go']['main']['App']['GetDescription']();
}

export function GetWindowHeight() {
  return window['go']['main']['App']['GetWindowHeight']();
}

export function GetYMax() {
  return window['go']['main']['App']['GetYMax']();
}

export function HandleAddonClick(arg1) {
  return window['go']['main']['App']['HandleAddonClick'](arg1);
}

export function HandleClick(arg1) {
  return window['go']['main']['App']['HandleClick'](arg1);
}

export function IsAddonMode() {
  return window['go']['main']['App']['IsAddonMode']();
}

export function IsRegularMode() {
  return window['go']['main']['App']['IsRegularMode']();
}

export function Reset() {
  return window['go']['main']['App']['Reset']();
}

export function SetWindowHeight(arg1) {
  return window['go']['main']['App']['SetWindowHeight'](arg1);
}

export function SetYMax(arg1) {
  return window['go']['main']['App']['SetYMax'](arg1);
}

export function StartAddonUsage() {
  return window['go']['main']['App']['StartAddonUsage']();
}

export function StartRegularUsage() {
  return window['go']['main']['App']['StartRegularUsage']();
}
